import "@permitojs/react/styles.css";
import { getConsentModeDefaultScript, readConsentFromCookieHeader } from "@permitojs/react/server";
import { headers } from "next/headers";
import type { ReactNode } from "react";
import { Providers } from "./providers";

export const metadata = { title: "Permito Next.js Beispiel" };

export default async function RootLayout({ children }: { children: ReactNode }) {
  // Reading the cookie on the server lets gated content render without a flash.
  const initialState = readConsentFromCookieHeader((await headers()).get("cookie"));
  return (
    <html lang="de-CH">
      <head>
        {/* Must run before any Google tag. Add your CSP nonce here if you use one. */}
        {/* biome-ignore lint/security/noDangerouslySetInnerHtml: static snippet generated by Permito */}
        <script dangerouslySetInnerHTML={{ __html: getConsentModeDefaultScript() }} />
      </head>
      <body>
        <Providers initialState={initialState}>{children}</Providers>
      </body>
    </html>
  );
}
